import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
        <div>バカ</div>
        <body style={{"border":"10px solid red"}}>
            {children}
        </body>
        <footer>Footer</footer>
    </html>
 )
}
